### ISSUE TITLE
Add Management feature

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#339] opened 2019-03-20 15:13 UTC
Some users should be elevated above normal users, but not have full admin privileges. In effect, these users might be called Managers, and be responsible for some groups, homes, and residents.

## Task
Explore how this feature might look and the functionality it might present.

**Comment by brylie** [comment] 2019-05-01 13:27
The basic example/user flow for this feature would be:

1. a `Group` is created (with one or more homes)
2. a `User` is assigned to that group as a 'manager'
3. that user can then perform the following actions for the group and homes therein:

- add `Residency` to `Home` (incl. creating a `Resident`)
- edit `Residency` associated with `Home` within the `Group`
- edit `Resident` associated with `Residency` linked to `Home` within the `Group`
    - this includes changing the name and setting `onHiatus`

**Comment by brylie** [comment] 2020-01-02 19:06
@shailee-m is this task complete?

**Comment by shailee-m** [comment] 2020-01-03 05:28
@brylie yes this is duplicate of #413

**Closed** 2020-01-03 09:41 UTC
Labels: enhancement
