### ISSUE TITLE
Console error (again) on resident profile with no activities

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#158] opened 2017-09-07 12:59 UTC
After refactoring the resident profile to use server aggregation, the console error has returned when a resident has no activities:

```
TypeError: Cannot read property 'value' of undefined
    at r (app.js?hash=303e9a7512d9edd0adff0312fb9a626509ec9c44:8790)
    at b (app.js?hash=303e9a7512d9edd0adff0312fb9a626509ec9c44:8790)
    at t.init (app.js?hash=303e9a7512d9edd0adff0312fb9a626509ec9c44:8792)
    at new t (app.js?hash=303e9a7512d9edd0adff0312fb9a626509ec9c44:8792)
    at Object.MG.data_graphic (app.js?hash=303e9a7512d9edd0adff0312fb9a626509ec9c44:8790)
    at Blaze.TemplateInstance.templateInstance.clearAndRenderChart (feelings.js:17)
    at Blaze.View.<anonymous> (feelings.js:76)
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1934
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744)
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1932
```

## Steps to reproduce
1. add new resident
2. visit resident profile (without adding any activities)
3. open browser console

Scenario, this but would appear when a new resident has moved in to a home and a staff member views their profile. Ideally, the page would say 'no activities added, add one now :-)' or something cheeky.

**Comment by marla-singer** [comment] 2019-01-25 20:21
@brylie Couldn't reproduce it. If resident doesn't have an activity then it's already shown message "Resident has no recorded activities."

![joxi_screenshot_1548446773611](https://user-images.githubusercontent.com/20643403/51770101-ed310580-20f5-11e9-9e12-35b32d7d278a.png)

Based on error message, the problem came from "feelings.js" file

```
at Blaze.TemplateInstance.templateInstance.clearAndRenderChart (feelings.js:17)
at Blaze.View.<anonymous> (feelings.js:76)
```

https://github.com/GeriLife/wellbeing/blob/281a04035efc2a1df8fb56ccbbb8e142c66bbfaa/app/client/views/resident/feelings/feelings.js#L42-L59

As I understood this issue was fixed by your commit 804daf6b148f205ee82755835cb34a1a3d873c11

If you remove the second part of condition when the error will appear

The bug isn't reproduced and can be closed

**Closed** 2019-01-25 21:10 UTC
Labels: Hacktoberfest, bug, good first issue, help wanted
